name: Upload and Deploy to OD2
on: [push]

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaino API JWT
        id: jwt_token
        run: |
          response=$(curl -s \
          -H "Accept: application/json" \
          -X POST https://api.nhsdigital.bloomreach.cloud/v3/authn/access_token \
          -d '{ "username": "${{ env.USERNAME }}", "password": "${{ env.PASSWORD }}" }')
          echo "::set-output name=token::${{fromJson($response).token_type}}
        env:
          API: ${{ secrets.MISSION_CONTROL_API_ADDRESS }}
          USERNAME: ${{ secrets.MISSION_CONTROL_API_USERNAME }}
          PASSWORD: ${{ secrets.MISSION_CONTROL_API_PASSWORD }}

      - name: Test Last step
        run: echo ${{ steps.jwt_token.outputs.token }}